title: "Il mio sito di test"
description: "Sito Jekyll con tema Minimal Mistakes"
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

markdown: kramdown
highlighter: rouge